"""Layers 2-4 on Linux: input colors, output colors and the prompt, per shell.

Each apply writes one generated init script per shell family into
~/.poshpalette/shell/ (bash, zsh, fish, and POSIX sh for ksh/mksh/dash/yash).
Each rc file only carries a fixed, one-line managed block that sources it, so
re-applying a theme never touches the rc again and `palette reset` removes it.

The init scripts also define a `palette` function that runs the picker and then
re-sources the script, so a new theme lands in the current shell without a
restart.
"""

import os
import pwd
import shlex
import shutil
from pathlib import Path

from . import files
from .catalog import home, user_root
from .colors import grep_colors, hex6, ls_colors, osc_sequence

OMP_THEME_URL = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/{}.omp.json"


def shell_dir():
    return user_root() / "shell"


def init_path(family):
    return shell_dir() / f"init.{family}"


def login_shell():
    sh = os.environ.get("SHELL")
    if not sh:
        try:
            sh = pwd.getpwuid(os.getuid()).pw_shell
        except (KeyError, OSError):
            sh = ""
    return os.path.basename(sh or "")


def q(s):
    """POSIX single-quote."""
    return shlex.quote(str(s))


def fq(s):
    """fish single-quote (only \\ and ' are special inside)."""
    return "'" + str(s).replace("\\", "\\\\").replace("'", "\\'") + "'"


def printf_osc(seq):
    """An OSC sequence as a printf format both sh and fish read the same way:
    ESC -> \\033 and the ST backslash -> \\134, so no quote escaping is needed."""
    return "".join("\\033" if c == "\x1b" else "\\134" if c == "\\" else c for c in seq)


# --- Per-shell input color maps -----------------------------------------------

def zsh_highlight_styles(prl):
    """zsh-syntax-highlighting main-highlighter styles from the input palette."""
    m = {
        "default": "Default", "unknown-token": "Error", "reserved-word": "Keyword",
        "alias": "Command", "suffix-alias": "Command", "global-alias": "Command", "builtin": "Command",
        "function": "Command", "command": "Command", "precommand": "Command", "hashed-command": "Command",
        "arg0": "Command", "autodirectory": "Command",
        "commandseparator": "Operator", "redirection": "Operator", "globbing": "Operator",
        "history-expansion": "Operator", "process-substitution-delimiter": "Operator",
        "command-substitution-delimiter": "Operator", "back-quoted-argument-delimiter": "Operator",
        "single-hyphen-option": "Parameter", "double-hyphen-option": "Parameter",
        "single-quoted-argument": "String", "double-quoted-argument": "String",
        "dollar-quoted-argument": "String", "back-quoted-argument": "String", "rc-quote": "String",
        "dollar-double-quoted-argument": "Variable", "back-double-quoted-argument": "Variable",
        "back-dollar-quoted-argument": "Variable", "assign": "Variable", "named-fd": "Variable",
        "numeric-fd": "Number", "comment": "Comment",
    }
    out = {k: f"fg=#{hex6(prl[r])}" for k, r in m.items() if prl.get(r)}
    if prl.get("Default"):
        out["path"] = f"fg=#{hex6(prl['Default'])},underline"
    return out


def fish_colors(prl, ps):
    m = {
        "fish_color_normal": "Default", "fish_color_command": "Command", "fish_color_keyword": "Keyword",
        "fish_color_quote": "String", "fish_color_redirection": "Operator", "fish_color_end": "Operator",
        "fish_color_operator": "Operator", "fish_color_error": "Error", "fish_color_param": "Default",
        "fish_color_option": "Parameter", "fish_color_comment": "Comment", "fish_color_escape": "Number",
        "fish_color_autosuggestion": "InlinePrediction",
        "fish_pager_color_prefix": "Command", "fish_pager_color_completion": "Default",
        "fish_pager_color_description": "Comment",
    }
    out = {k: hex6(prl[r]) for k, r in m.items() if prl.get(r)}
    if ps.get("Directory"):
        out["fish_color_cwd"] = hex6(ps["Directory"])
    return out


def ble_faces(prl):
    """ble.sh (bash syntax highlighting) faces."""
    m = {
        "command_builtin": "Command", "command_alias": "Command", "command_function": "Command",
        "command_file": "Command", "command_keyword": "Keyword", "syntax_quoted": "String",
        "syntax_quotation": "String", "syntax_comment": "Comment", "syntax_error": "Error",
        "syntax_delimiter": "Operator", "varname_normal": "Variable", "argument_option": "Parameter",
        "auto_complete": "InlinePrediction",
    }
    return {k: f"fg=#{hex6(prl[r])}" for k, r in m.items() if prl.get(r)}


# --- Script generation --------------------------------------------------------

def _header(theme):
    return [
        "# Generated by PoshPalette - rewritten on every apply. Don't edit:",
        "# change the look with `palette`, remove it with `palette reset`.",
        f"# Theme: {theme.get('name') or theme['terminal']['scheme'].get('name')}",
    ]


SH_TERM_FN = r"""__pp_term() {
  if [ "${TERM_PROGRAM-}" = ghostty ] || [ "${TERM-}" = xterm-ghostty ] || [ -n "${GHOSTTY_RESOURCES_DIR-}" ]; then echo ghostty
  elif [ -n "${KITTY_WINDOW_ID-}" ] || [ "${TERM-}" = xterm-kitty ]; then echo kitty
  elif [ -n "${ALACRITTY_WINDOW_ID-}" ] || [ -n "${ALACRITTY_SOCKET-}" ] || [ "${TERM-}" = alacritty ]; then echo alacritty
  else case "${TERM-}" in foot*) echo foot ;; *) echo other ;; esac
  fi
}"""

FISH_TERM_FN = r"""function __pp_term
    if test "$TERM_PROGRAM" = ghostty; or test "$TERM" = xterm-ghostty; or set -q GHOSTTY_RESOURCES_DIR
        echo ghostty
    else if set -q KITTY_WINDOW_ID; or test "$TERM" = xterm-kitty
        echo kitty
    else if set -q ALACRITTY_WINDOW_ID; or set -q ALACRITTY_SOCKET; or test "$TERM" = alacritty
        echo alacritty
    else if string match -q 'foot*' -- "$TERM"
        echo foot
    else
        echo other
    end
end"""


def _sh_osc(theme, managed):
    seq = printf_osc(osc_sequence(theme["terminal"]["scheme"]))
    skip = "|".join(managed) if managed else "__none__"
    return [
        "# Terminal colors via OSC, for terminals whose config PoshPalette doesn't write.",
        SH_TERM_FN,
        'if [ -t 1 ] && [ -z "${TMUX-}" ] && [ -z "${STY-}" ]; then',
        '  case "${TERM-}" in dumb|linux|"") ;; *)',
        f'    case "$(__pp_term)" in {skip}) ;; *) printf \'{seq}\' ;; esac ;;',
        "  esac",
        "fi",
        "unset -f __pp_term",
    ]


def _sh_output(theme):
    lines = ["# Output colors (ls, eza, fd, tree, grep)"]
    lc, gc = ls_colors(theme), grep_colors(theme)
    if lc:
        lines.append(f"export LS_COLORS={q(lc)}")
    if gc:
        lines.append(f"export GREP_COLORS={q(gc)}")
    return lines


def _omp_config_expr(theme, prompt_path):
    """(kind, value): 'path' with a generated config path, or 'name' for a
    referenced oh-my-posh theme, or None when the theme has no prompt."""
    p = theme.get("prompt") or {}
    if p.get("generated") and prompt_path:
        return "path", str(prompt_path)
    if p.get("ohMyPoshTheme"):
        return "name", p["ohMyPoshTheme"]
    return None


def _sh_prompt(shell, theme, prompt_path):
    cfg = _omp_config_expr(theme, prompt_path)
    if not cfg:
        return []
    lines = ["# Prompt (oh-my-posh). Inert until oh-my-posh is installed.", "if command -v oh-my-posh >/dev/null 2>&1; then"]
    if cfg[0] == "path":
        lines.append(f'  eval "$(oh-my-posh init {shell} --config {q(cfg[1])})"')
    else:
        name = cfg[1]
        lines += [
            f'  __pp_cfg="${{POSH_THEMES_PATH:-$HOME/.cache/oh-my-posh/themes}}/{name}.omp.json"',
            f'  [ -f "$__pp_cfg" ] || __pp_cfg={q(OMP_THEME_URL.format(name))}',
            f'  eval "$(oh-my-posh init {shell} --config "$__pp_cfg")"',
            "  unset __pp_cfg",
        ]
    lines.append("fi")
    return lines


def _sh_palette_fn(cli, family):
    init = init_path(family)
    return [
        "# `palette` runs the picker, then reloads this file so the new look lands here.",
        "palette() {",
        f'  command {q(cli)} "$@"',
        "  set -- $?",
        f"  if [ -f {q(init)} ]; then . {q(init)}; fi",
        '  return "$1"',
        "}",
    ]


def zsh_script(theme, managed, prompt_path, cli):
    prl = theme["psReadLine"]
    lines = _header(theme) + ["[[ -o interactive ]] || return 0", ""]
    lines += _sh_osc(theme, managed) + [""]
    lines += _sh_output(theme)
    lines += ["zstyle ':completion:*' list-colors \"${(s.:.)LS_COLORS}\"", ""]
    lines += ["# Input colors (zsh-syntax-highlighting, zsh-autosuggestions)", "typeset -gA ZSH_HIGHLIGHT_STYLES"]
    lines += [f"ZSH_HIGHLIGHT_STYLES[{k}]={q(v)}" for k, v in zsh_highlight_styles(prl).items()]
    if prl.get("InlinePrediction"):
        lines.append(f"typeset -g ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE={q('fg=#' + hex6(prl['InlinePrediction']))}")
    lines.append("")
    lines += _sh_prompt("zsh", theme, prompt_path) + [""]
    lines += _sh_palette_fn(cli, "zsh")
    return "\n".join(lines) + "\n"


def bash_script(theme, managed, prompt_path, cli):
    lines = _header(theme) + ["case $- in *i*) ;; *) return 0 ;; esac", ""]
    lines += _sh_osc(theme, managed) + [""]
    lines += _sh_output(theme) + [""]
    faces = ble_faces(theme["psReadLine"])
    if faces:
        lines += ["# Input colors (only with ble.sh - plain readline has no syntax highlighting)",
                  'if [ -n "${BLE_VERSION-}" ]; then']
        lines += [f"  ble-face -s {k} {q(v)} 2>/dev/null" for k, v in faces.items()]
        lines += ["fi", ""]
    lines += _sh_prompt("bash", theme, prompt_path) + [""]
    lines += _sh_palette_fn(cli, "bash")
    return "\n".join(lines) + "\n"


def sh_script(theme, managed, prompt_path, cli):
    """POSIX sh (ksh, mksh, dash, yash): terminal + output colors. oh-my-posh has
    no init for these shells, so there's no prompt layer."""
    lines = _header(theme) + ["case $- in *i*) ;; *) return 0 ;; esac", ""]
    lines += _sh_osc(theme, managed) + [""]
    lines += _sh_output(theme) + [""]
    lines += _sh_palette_fn(cli, "sh")
    return "\n".join(lines) + "\n"


def fish_script(theme, managed, prompt_path, cli):
    seq = printf_osc(osc_sequence(theme["terminal"]["scheme"]))
    lines = _header(theme) + ["status is-interactive; or return", ""]
    lines += ["# Terminal colors via OSC, for terminals whose config PoshPalette doesn't write.", FISH_TERM_FN]
    lines += ["if isatty stdout; and not set -q TMUX; and not set -q STY; and not contains -- \"$TERM\" dumb linux ''"]
    if managed:
        lines += [f"    if not contains -- (__pp_term) {' '.join(managed)}", f"        printf '{seq}'", "    end"]
    else:
        lines += [f"    printf '{seq}'"]
    lines += ["end", "functions -e __pp_term", ""]
    lines += ["# Output colors (ls, eza, fd, tree, grep)"]
    lc, gc = ls_colors(theme), grep_colors(theme)
    if lc:
        lines.append(f"set -gx LS_COLORS {fq(lc)}")
    if gc:
        lines.append(f"set -gx GREP_COLORS {fq(gc)}")
    lines += ["", "# Input colors (fish syntax highlighting)"]
    lines += [f"set -g {k} {v}" for k, v in fish_colors(theme["psReadLine"], theme["psStyle"]).items()]
    lines.append("")
    cfg = _omp_config_expr(theme, prompt_path)
    if cfg:
        lines += ["# Prompt (oh-my-posh). Inert until oh-my-posh is installed.", "if type -q oh-my-posh"]
        if cfg[0] == "path":
            lines.append(f"    oh-my-posh init fish --config {fq(cfg[1])} | source")
        else:
            name = cfg[1]
            lines += [
                "    set -l __pp_dir $HOME/.cache/oh-my-posh/themes",
                "    set -q POSH_THEMES_PATH; and set __pp_dir $POSH_THEMES_PATH",
                f"    set -l __pp_cfg $__pp_dir/{name}.omp.json",
                f"    test -f $__pp_cfg; or set __pp_cfg {fq(OMP_THEME_URL.format(name))}",
                "    oh-my-posh init fish --config $__pp_cfg | source",
            ]
        lines += ["end", ""]
    init = init_path("fish")
    lines += [
        "# `palette` runs the picker, then reloads this file so the new look lands here.",
        "function palette",
        f"    command {fq(cli)} $argv",
        "    set -l rc $status",
        f"    test -f {fq(init)}; and source {fq(init)}",
        "    return $rc",
        "end",
    ]
    return "\n".join(lines) + "\n"


GENERATORS = {"zsh": zsh_script, "bash": bash_script, "fish": fish_script, "sh": sh_script}


# --- rc wiring ----------------------------------------------------------------

class Shell:
    def __init__(self, name, family, binary, rc):
        self.name, self.family, self.binary, self._rc = name, family, binary, rc

    def rc_path(self):
        return self._rc()

    def installed(self):
        return bool(shutil.which(self.binary))

    def should_wire(self):
        """Wire a shell that's installed and actually used: its rc exists, or it's
        the login shell. fish loads conf.d on its own, so installed is enough."""
        if not self.installed():
            return False
        if self.name == "fish":
            return True
        return self.rc_path().exists() or login_shell() == self.name

    def wire_body(self):
        init = init_path(self.family)
        if self.name == "fish":
            return None
        return f"if [ -f {q(init)} ]; then . {q(init)}; fi"

    def wire(self, dry_run=False):
        if self.name == "fish":
            loader = self.rc_path()
            init = init_path("fish")
            text = ("# PoshPalette loader - removed by `palette reset`.\n"
                    f"test -f {fq(init)}; and source {fq(init)}\n")
            return files.write_generated(loader, text, dry_run)
        return files.upsert_block(self.rc_path(), self.wire_body(), dry_run=dry_run)

    def unwire(self, dry_run=False):
        if self.name == "fish":
            p = self.rc_path()
            if p.exists():
                if not dry_run:
                    p.unlink()
                return True
            return False
        return files.remove_block(self.rc_path(), dry_run)

    def wired(self):
        if self.name == "fish":
            return self.rc_path().exists()
        return files.has_block(self.rc_path())


def _zdotdir():
    return Path(os.environ.get("ZDOTDIR") or home())


def _fish_conf():
    return Path(os.environ.get("XDG_CONFIG_HOME") or home() / ".config") / "fish" / "conf.d" / "posh-palette.fish"


SHELLS = (
    Shell("zsh", "zsh", "zsh", lambda: _zdotdir() / ".zshrc"),
    Shell("bash", "bash", "bash", lambda: home() / ".bashrc"),
    Shell("fish", "fish", "fish", _fish_conf),
    Shell("ksh", "sh", "ksh", lambda: home() / ".kshrc"),
    Shell("mksh", "sh", "mksh", lambda: home() / ".mkshrc"),
)


def write_init_scripts(theme, managed, prompt_path, cli, dry_run=False):
    """Generate every init script. Returns the paths that changed."""
    changed = []
    for family, gen in GENERATORS.items():
        p = init_path(family)
        if files.write_generated(p, gen(theme, managed, prompt_path, cli), dry_run):
            changed.append(p)
    return changed


def remove_init_scripts(dry_run=False):
    removed = []
    for family in GENERATORS:
        p = init_path(family)
        if p.exists():
            if not dry_run:
                p.unlink()
            removed.append(p)
    return removed
